version: "3.5"

services:
  #simpletracker:
  #  image: sky360/simpletracker-ros2:1.0.2
  #  ports:
  #    - '8080:8080'
  #  #networks:
  #  #  - sky360
  #  network_mode: host

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    #networks:
    #  - sky360
    network_mode: host
    volumes:
      - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    #networks:
    #  - sky360
    network_mode: host
    volumes:
      - prometheus:/prometheus
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

#networks:
#  sky360:
#    name: sky360-network
#    external: true

volumes:
  grafana:
    driver: local
  prometheus:
    driver: local