global:
  scrape_interval: 15s
  external_labels:
    monitor: 'statistics-monitor'

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'sky360-tracker'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8082']
  - job_name: 'sky360-dds'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']         