configuration_service:
  ros__parameters:
    video_file: "Test_Trimmed.mp4"
    tracker_type: "CSRT"
    background_subtractor_type: "KNN"
    mask_type: "overlay_inverse"
    mask_pct: 5
    mask_overlay_image_file_name: "mask-shrubs-inverse-overlay.jpg"
    visualiser_frame_source: "original"